### ISSUE TITLE
Cannot open file 'detours.lib'

### ISSUE THREAD

**Issue by qvimxyz** [rushensky2h/cs16_frame_skip#1]
LINK : fatal error LNK1104: cannot open file 'detours.lib'

**Comment by rushensky2h** [comment]
Rename in "MinHook.lib"

**Comment by qvimxyz** [comment]
same issue
![bn](https://user-images.githubusercontent.com/44214566/106381215-011f3a00-6396-11eb-926a-c598c04ec656.png)

**Comment by rushensky2h** [comment]
download this: https://github.com/TsudaKageyu/minhook/releases/tag/v1.3.3
